import React from 'react';
import { Download, Share2, ArrowRight, TrendingUp, TrendingDown } from 'lucide-react';
import { FinalReport as FinalReportType } from '../types/index';

interface FinalReportProps {
  analysisId: string;
  report: FinalReportType;
  startupName: string;
  onNavigate: (screen: string) => void;
}

const FinalReport: React.FC<FinalReportProps> = ({
  analysisId,
  report,
  startupName,
  onNavigate,
}) => {
  const getScoreColor = (score: number) => {
    if (score >= 8) return 'text-success';
    if (score >= 6) return 'text-warning';
    return 'text-error';
  };

  const getRiskColor = (score: number) => {
    if (score <= 3) return 'text-success';
    if (score <= 6) return 'text-warning';
    return 'text-error';
  };

  const isPositiveRecommendation = report.recommendation.toLowerCase().includes('buy');

  return (
    <div className="min-h-screen bg-bg-light">
      <nav className="sticky top-0 z-50 bg-white border-b border-border shadow-xs">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <button
            onClick={() => onNavigate('landing')}
            className="text-2xl font-bold text-accent hover:opacity-80 transition tracking-wide"
          >
            ✦ VentureMind AI
          </button>
        </div>
      </nav>

      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        {/* Header */}
        <div className="mb-12">
          <h1 className="text-4xl font-bold text-text-primary mb-2">
            Final Investment Report: <span className="text-accent">{startupName}</span>
          </h1>
          <p className="text-text-secondary">Analysis ID: {analysisId} • Generated by VentureMind AI</p>
        </div>

        {/* Main Recommendation */}
        <div
          className={`rounded-lg p-8 mb-12 border ${
            isPositiveRecommendation
              ? 'bg-success/10 border-success/30'
              : 'bg-warning/10 border-warning/30'
          }`}
        >
          <div className="flex items-center space-x-4 mb-4">
            {isPositiveRecommendation ? (
              <TrendingUp className="w-8 h-8 text-success" />
            ) : (
              <TrendingDown className="w-8 h-8 text-warning" />
            )}
            <h2 className="text-3xl font-bold text-text-primary">Investment Recommendation</h2>
          </div>
          <p
            className={`text-2xl font-bold ${
              isPositiveRecommendation ? 'text-success' : 'text-warning'
            }`}
          >
            {report.recommendation}
          </p>
        </div>

        {/* Key Scores */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
          {/* Founder Score */}
          <div className="card bg-bg-card">
            <p className="text-text-secondary text-sm mb-3">Founder Score</p>
            <div className="flex items-end justify-between">
              <div>
                <p className={`text-4xl font-bold ${getScoreColor(report.founder_score)}`}>
                  {report.founder_score.toFixed(1)}
                </p>
                <p className="text-text-tertiary text-sm mt-2">out of 10</p>
              </div>
              <div className="flex-1 ml-4">
                <div className="w-full bg-bg-light rounded-full h-3 border border-border overflow-hidden">
                  <div
                    className="bg-accent h-full"
                    style={{ width: `${(report.founder_score / 10) * 100}%` }}
                  />
                </div>
              </div>
            </div>
          </div>

          {/* Market Score */}
          <div className="card bg-bg-card">
            <p className="text-text-secondary text-sm mb-3">Market Score</p>
            <div className="flex items-end justify-between">
              <div>
                <p className={`text-4xl font-bold ${getScoreColor(report.market_score)}`}>
                  {report.market_score.toFixed(1)}
                </p>
                <p className="text-text-tertiary text-sm mt-2">out of 10</p>
              </div>
              <div className="flex-1 ml-4">
                <div className="w-full bg-bg-light rounded-full h-3 border border-border overflow-hidden">
                  <div
                    className="bg-success h-full"
                    style={{ width: `${(report.market_score / 10) * 100}%` }}
                  />
                </div>
              </div>
            </div>
          </div>

          {/* Risk Score */}
          <div className="card bg-bg-card">
            <p className="text-text-secondary text-sm mb-3">Risk Score</p>
            <div className="flex items-end justify-between">
              <div>
                <p className={`text-4xl font-bold ${getRiskColor(10 - report.risk_score)}`}>
                  {(10 - report.risk_score).toFixed(1)}
                </p>
                <p className="text-text-tertiary text-sm mt-2">Safety (out of 10)</p>
              </div>
              <div className="flex-1 ml-4">
                <div className="w-full bg-bg-light rounded-full h-3 border border-border overflow-hidden">
                  <div
                    className="bg-warning h-full"
                    style={{ width: `${((10 - report.risk_score) / 10) * 100}%` }}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Detailed Report */}
        <div className="card bg-bg-card mb-12">
          <h3 className="text-2xl font-bold text-accent mb-6">Detailed Analysis</h3>
          <div className="bg-bg-light rounded-lg p-6 border border-border">
            <div className="max-w-none">
              {report.report.split('\n').map((line, index) => {
                if (line.startsWith('##')) {
                  return (
                    <h3 key={index} className="text-xl font-bold text-accent mt-6 mb-3">
                      {line.replace('## ', '')}
                    </h3>
                  );
                }
                if (line.startsWith('###')) {
                  return (
                    <h4 key={index} className="text-lg font-semibold text-text-primary/80 mt-4 mb-2">
                      {line.replace('### ', '')}
                    </h4>
                  );
                }
                if (line.startsWith('-')) {
                  return (
                    <li key={index} className="text-text-primary/80 ml-6 mb-2">
                      {line.replace('- ', '')}
                    </li>
                  );
                }
                if (line.trim() === '') {
                  return <div key={index} className="my-2" />;
                }
                return (
                  <p key={index} className="text-text-primary/80 mb-2 leading-relaxed">
                    {line}
                  </p>
                );
              })}
            </div>
          </div>
        </div>

        {/* Summary Stats */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-12">
          <div className="card bg-bg-card">
            <p className="text-text-secondary text-sm mb-2">Analysis Status</p>
            <p className="text-text-primary font-semibold">✓ Complete</p>
          </div>
          <div className="card bg-bg-card">
            <p className="text-text-secondary text-sm mb-2">Report Type</p>
            <p className="text-text-primary font-semibold">Comprehensive Investment Analysis</p>
          </div>
        </div>

        {/* Actions */}
        <div className="flex flex-col sm:flex-row gap-4">
          <button className="btn-primary flex-1 flex items-center justify-center space-x-2">
            <Download className="w-5 h-5" />
            <span>Download PDF</span>
          </button>
          <button className="btn-primary flex-1 flex items-center justify-center space-x-2">
            <Share2 className="w-5 h-5" />
            <span>Share Report</span>
          </button>
        </div>

        {/* Navigation */}
        <div className="flex justify-between mt-12 pt-8 border-t border-border">
          <button
            onClick={() => onNavigate('debate')}
            className="btn-secondary"
          >
            ← Back to Debate
          </button>
          <button
            onClick={() => onNavigate('digital-twin')}
            className="btn-primary flex items-center space-x-2"
          >
            <span>Digital Twin Analysis</span>
            <ArrowRight className="w-5 h-5" />
          </button>
        </div>
      </div>
    </div>
  );
};

export default FinalReport;
